### ISSUE TITLE
343行的<phrase id="SearchBtn"应改成<phrase id="SearchLink"

### ISSUE THREAD

**Issue by szmufo** [malsony/PHPMaker-Chinese-Simplified-xml#2]
343行的<phrase id="SearchBtn"应改成<phrase id="SearchLink"

**Comment by malsony** [comment]
谢谢指出！不知道为什么好多码不对应，晕

**Comment by szmufo** [comment]
不客气，你加我QQ吧 150009100 交个朋友





------------------ 原始邮件 ------------------
发件人: "malsony";<notifications@github.com>;
发送时间: 2017年8月4日(星期五) 下午3:16
收件人: "malsony/PHPMaker-Chinese-Simplified-xml"<PHPMaker-Chinese-Simplified-xml@noreply.github.com>; 
抄送: "绝世名伶"<szmufo@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [malsony/PHPMaker-Chinese-Simplified-xml] 343行的<phrase id="SearchBtn"应改成<phrase id="SearchLink" (#2)




谢谢指出！不知道为什么好多码不对应，晕
